### ISSUE TITLE
Arrow not included in nuget package.

### ISSUE THREAD

**Issue by trungnt2910** [enisn/TreeView.Maui#11]
The arrows from [here](https://github.com/enisn/TreeView.Maui/tree/main/src/TreeView.Maui/Resources) are [not included](https://nuget.info/packages/TreeView.Maui/1.0.2) in the NuGet package, requiring the user to manually include these resources in the project.

**Comment by enisn** [comment]
I didn't aware of that problem, I just created a maui class library template and it says, build action is `MauiImage` but it doesn't include them in built assembly.

PR #12 makes them Embedded Resource
