### ISSUE TITLE
Missing ViewUpdate for toggle arrows and node names

### ISSUE THREAD

**Issue by mlototchi** [enisn/TreeView.Maui#13]
Nice work so far. Updating the view after adding/removing nodes works fine.
Thanks for that, but there are still two little problems.

First: If you add a new node to a node, which have no child nodes yet (and no shown toggle arrow), the view does not update the appereance of the toggle arrows, so they are still invisible

Second: There is no view update, after changing the name of a node

**Comment by enisn** [comment]
I see,

[IsLeaf](https://github.com/enisn/TreeView.Maui/blob/main/src/TreeView.Maui/Core/TreeViewNode.cs#L29) and [Name](https://github.com/enisn/TreeView.Maui/blob/main/src/TreeView.Maui/Core/TreeViewNode.cs#L24) property should trigger `PropertyChanged` event. I'll handle it
