### ISSUE TITLE
Some problems with the last update

### ISSUE THREAD

**Issue by mlototchi** [enisn/TreeView.Maui#15]
Hi, something went wrong in the last update.

Adding a child node to a 'leaf' node still does not cause the toggle arrows to appear.

Furthermore, when you fold in a node, it can no longer be unfolded

**Comment by enisn** [comment]
Sorry, I implemented in wrong before. The new implementation (#17) works well.
![treeview-sample](https://user-images.githubusercontent.com/23705418/189521693-a09abae8-1d56-49da-9d12-5b01d337d5d8.gif)
