### ISSUE TITLE
View is not updated after adding/removing subnodes

### ISSUE THREAD

**Issue by mlototchi** [enisn/TreeView.Maui#7]
The collectionChanged event only of the root-nodes-collection causes an update of the view, but not the collections of the subnodes.
Looking at the code, i guess it is because the invoking of a render-Method like in your TreeView Class is missing in the TreeViewNodeView Class

**Comment by enisn** [comment]
Yes, subnodes collection isn't ObservableCollection at the moment. I'll work on it
